docs/hpc/advanced/debugging_mpi_programs/debugging_overview.md
docs/hpc/advanced/debugging_mpi_programs/gdb_mpi_debug.md
mkdocs.yml

In this PR, I have added some documentation about the debuggers and how we can use GDB to debug an MPI program. In the absence of a commercial debugger, this would prove useful to the users who are developing their own code.

How to use GDB to debug MPI program

---

mkdocs.yml

Minor fix to spelling mistake on navigation bar.

Fix to minor spelling mistake on navigation bar.

---

docs/rds/transferringdata/index.md
docs/rds/transferringdata/rclone.md
mkdocs.yml

Initial pass of documentation for rclone. Welcome any comments/feedback.

Added documentation for rclone.

---

docs/hpc/faq/not-enough-slots.md
docs/hpc/faq/python-multiprocessing.md
mkdocs.yml

In this PR, we add the documentation for two issues.
1. First is the MPI slot issues as encountered in CS0468781. I have now added the error message and how to resolve it.
2. Second issue is the Python multiprocessing issue. This was raised in CS0469983. I have added the advise which may help to resolve the issue.

Python multilprocessing and MPI slots

---

docs/hpc/cluster-specification.md
docs/hpc/pilot/cx3-phase2.md

Updated  cx3 phase 2 documentation and added some details for Conda/Python users to help them move over easily.

L40s and python

---

docs/hpc/queues/job-sizing-guidance.md

I have removed and/or updated the information about the general and interactive queues.

Removed General and interactive 

---

docs/Workshops/Intel/one_api_programming.md
docs/Workshops/Intel/openmp_offloading.md

I have updated the workshop timings and venue details.
We have also added the links so that people can register.

Intel workshop timing details

---

docs/Workshops/Intel/one_api_programming.md

I have added some catering details in this PR so that participants can plan accordingly.

Added catering details for the One api workshop

---

docs/hpc/pilot/cx3-phase2.md

I have confirmed the numbers and added links to the NVidia data sheets. I have also rotated the table so the information fits on the screen better

Updated Spec GPU

---

docs/Workshops/hacktoberfest.md
docs/Workshops/overview.md
mkdocs.yml

As suggested by @EmChem79 to promote the event.

:sparkles: Add Hacktoberfest event organised by the RSE team

---

docs/Workshops/Intel/openmp_offloading.md

The open mp offload workshop date was changed recently. In this PR, I have changed the appropriate details to reflect the same.

Updated openmp workshop details

---

docs/hpc/pilot/cx3-phase2.md
docs/hpc/pilot/hx1.md

Updated the Python+Conda advice on Phase 2 to align with other pages in the docs. I have also added a bit more to the HX1 page to encourage AI users to try the L40s nodes first.

Phase 2 Conda

---

docs/hpc/getting-started/using-ssh.md
docs/support/using-linux/command-line.md

Details on how to enable Mirror mode in WSL

Using WSL to connect to IPv6 servers

---

docs/hpc/applications/guides/starccm.md

Simple example that uses Intel MPI and IPv6 networking

StarCCM+ and IPv6

---

docs/hpc/pilot/hx1.md

Let me know if you see any issues with any of the values/formatting.
Fixes issue #32

added table for HX1 job sizing

---

docs/hpc/pilot/cx3-phase2.md

Updated queues and general GPU information. I have also put a strikethrough on the largemem queue as it can't be used on Phase 2 at the moment and users are requesting it.

Updated GPU information

---

docs/hpc/pilot/cx3-phase2.md

Jhub11 kernels

---

docs/hpc/applications/guides/abaqus.md

Based on advice from CS0614473

Abaque vis

---

docs/hpc/cluster-specification.md
docs/hpc/pilot/cx3-phase2.md
docs/hpc/queues/checkpointing.md

Made the layout more readable as well as updated date and figures to be more accurate.

Cluster spec update

---

docs/hpc/faq/blas_multicore_issue.md
mkdocs.yml

This PR addresses an issue where users were trying to run Blas codes on multiple cores and were facing issues.

Running blas on multiple cores

---

docs/hpc/applications/guides/matlab.md
docs/hpc/applications/guides/python.md

CS0631845
In this ticket, the user was interested to run Python code from matalb. 
The current pull request gives a small example on how people can run a Python code from Matlab.

Python from matlab

---

docs/hpc/applications/guides/matlab.md
docs/hpc/applications/guides/python.md

CS0617983
In this PR (based on the above ticket), we add details on how people can run Matlab code from Python.
This is basically the reverse of #60.

Matlab code from python
